function out = convertUnits(val, fromUnit, toUnit)
%CONVERTUNITS  Scale a value (or array) between common units.
%
%   out = convertUnits(val, fromUnit, toUnit)
%
% Handles the conversions commonly needed in physiology plotting:
%   time           : s, ms, min, hour
%   frequency/rate : Hz, bpm, cpm, rpm  (note bpm/cpm/rpm are equal)
%   fraction       : %  <->  fraction
%   voltage        : V, mV, uV
%
% Behaviour
%   - Empty / matching units return val unchanged.
%   - Unknown unit pair issues a warning once per pair and returns val.
%   - Vectorised on val.

    fromUnit = strtrim(char(fromUnit));
    toUnit   = strtrim(char(toUnit));

    if isempty(fromUnit) || isempty(toUnit) || strcmpi(fromUnit, toUnit)
        out = val;
        return;
    end

    f = unitFactor(fromUnit, toUnit);
    if isnan(f)
        warning('convertUnits:unknown', ...
            'No conversion known for %s -> %s; returning value unchanged.', ...
            fromUnit, toUnit);
        out = val;
    else
        out = val * f;
    end
end


function f = unitFactor(from, to)
% Look up the multiplicative factor: val_in_to = val_in_from * f.
    table = { ...
        's',        'ms',        1e3;       ...
        's',        'min',       1/60;      ...
        's',        'minute',    1/60;      ...
        's',        'hour',      1/3600;    ...
        'ms',       'min',       1/60000;   ...
        'min',      'hour',      1/60;      ...
        'Hz',       'bpm',       60;        ...
        'Hz',       'cpm',       60;        ...
        'Hz',       'rpm',       60;        ...
        'bpm',      'cpm',       1;         ...
        'bpm',      'rpm',       1;         ...
        'cpm',      'rpm',       1;         ...
        'bpm',      'breaths/min', 1;       ...
        'bpm',      'beats/min',   1;       ...
        '%',        'fraction',  1/100;     ...
        '%',        'percent',   1;         ...
        'V',        'mV',        1e3;       ...
        'V',        'uV',        1e6;       ...
        'mV',       'uV',        1e3;       ...
        };

    for k = 1:size(table,1)
        if strcmpi(table{k,1}, from) && strcmpi(table{k,2}, to)
            f = table{k,3}; return;
        end
        if strcmpi(table{k,1}, to) && strcmpi(table{k,2}, from)
            f = 1 / table{k,3}; return;
        end
    end
    f = NaN;
end
